apiVersion: v1
kind: Service

metadata:
  name: goserver-service

spec:

    type: LoadBalancer
    ports:
      - port: 3000
        name: http-svc
        protocol: TCP

    selector:
      app: server